---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-off-app
spec:
  selector:
    matchLabels:
      app: time-off-app
  template:
    metadata:
      labels:
        app: time-off-app
    spec:
      containers:
      - name: time-off-app
        image: us-central1-docker.pkg.dev/gorilla-375616/time-off-gorilla/time-off-image:latest
        ports:
          - containerPort: 3000
